# Build the manager binary

# Define a default value for GO_VERSION if not passed
ARG GO_VERSION=1.25

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-bookworm

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
RUN mkdir -p /root/.kube
#COPY /tmp/kubeconfig $HOME/.kube/config 
COPY main.go main.go
COPY cmd/ cmd/
COPY apis/ apis/
COPY controllers/ controllers/
COPY internal/ internal/
COPY docs/ docs/

#RUN CGO_ENABLED=0 go build -a -o manager main.go
RUN CGO_ENABLED=0 go build -a -o pac-go-server ./cmd/pac-go-server
#RUN CGO_ENABLED=0 go build -a -o event-notifier ./cmd/event-notifier

ENTRYPOINT ["./pac-go-server"]

